---
title: 'Exercise 3: Kable Tables'
author: "Matthew Bass"
date: "20/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown Exercise

This exercise is used to develop a sample report using the `LOS_model` dataset from the `NHSRdatasets` package.
More information about this package is avaialble [here](https://cran.r-project.org/web/packages/NHSRdatasets/index.html).

```{r load, echo = FALSE, message=FALSE, warning=FALSE}
# Load the data set here
library(NHSRdatasets)
library(dplyr)
library(kableExtra)
data(LOS_model)
```

## Full dataset

Here is the full LOS_model dataset printed with kable.

```{r}


# Exercise 3 Add in parameters to the kable() function below and then pipe in the `kable styling` function in the line below that


```


## Full dataset statistics

Here is a summary of the LOS using `dplyr`. It uses Kable to make the table look a bit nicer.

```{r summary, message=FALSE}

# Exercise 3 continued -

# Produce a new variable to store a copy of the LOS_model and then pipe in the summarise function, using the mean and median functions on the relevant columns of your choice.  Finally, use kable and kable styling to output the summarised model


```

